// Définir un type pour une offre d'emploi (facultatif mais recommandé)
export type Job = {
  id: string;
  title: string;
  company: string;
  location: string;
  type: string; // e.g., CDI, CDD, Freelance
  salary: string;
  posted: string;
  description: string;
  tags: string[];
  isNew: boolean;
  isUrgent: boolean;
};


const jobsData: Job[] = [
  {
    id: "1",
    title: "Ingénieur Logiciel Senior",
    company: "TechCorp Solutions",
    location: "Douala, Cameroun (À distance)",
    type: "CDI",
    salary: "800k - 1.2M FCFA",
    posted: "Il y a 2 jours",
    description: "Nous recherchons un ingénieur logiciel expérimenté pour rejoindre notre équipe plateforme. Vous travaillerez sur la construction de systèmes distribués évolutifs qui alimentent nos produits.",
    tags: ["React", "TypeScript", "Node.js", "AWS"],
    isNew: true,
    isUrgent: false,
  },
  {
    id: "2",
    title: "Designer Produit",
    company: "DesignHub Inc",
    location: "Yaoundé, Cameroun",
    type: "CDI",
    salary: "600k - 900k FCFA",
    posted: "Il y a 1 semaine",
    description: "Rejoignez notre équipe de design pour créer de belles expériences centrées sur l'utilisateur. Vous collaborerez avec les ingénieurs et les chefs de produit.",
    tags: ["Figma", "UI/UX", "Design Systems", "Prototyping"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "3",
    title: "Data Scientist",
    company: "Analytics Pro",
    location: "Douala, Cameroun (Hybride)",
    type: "CDI",
    salary: "700k - 1M FCFA",
    posted: "Il y a 3 jours",
    description: "Recherche d'un data scientist pour nous aider à extraire des insights à partir de datasets complexes et construire des modèles de machine learning.",
    tags: ["Python", "Machine Learning", "SQL", "TensorFlow"],
    isNew: true,
    isUrgent: true,
  },
  {
    id: "4",
    title: "Développeur Frontend",
    company: "WebWorks Studio",
    location: "Yaoundé, Cameroun (À distance)",
    type: "Freelance",
    salary: "500k - 700k FCFA",
    posted: "Il y a 1 jour",
    description: "Nous avons besoin d'un développeur frontend talentueux pour construire des applications web responsives et accessibles.",
    tags: ["React", "JavaScript", "CSS", "Accessibility"],
    isNew: true,
    isUrgent: false,
  },
  {
    id: "5",
    title: "Ingénieur DevOps",
    company: "CloudSystems Ltd",
    location: "Bafoussam, Cameroun",
    type: "CDI",
    salary: "750k - 1.1M FCFA",
    posted: "Il y a 5 jours",
    description: "Rejoignez notre équipe infrastructure pour construire et maintenir des pipelines CI/CD, automatiser les déploiements.",
    tags: ["Docker", "Kubernetes", "AWS", "Terraform"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "6",
    title: "Responsable Marketing",
    company: "GrowthTech",
    location: "Douala, Cameroun (Hybride)",
    type: "CDI",
    salary: "550k - 850k FCFA",
    posted: "Il y a 1 semaine",
    description: "Dirigez nos initiatives marketing pour stimuler la notoriété de la marque et l'acquisition de clients.",
    tags: ["Marketing Digital", "SEO", "Stratégie de contenu", "Analytics"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "7",
    title: "Développeur Mobile",
    company: "AppMasters",
    location: "Yaoundé, Cameroun (À distance)",
    type: "CDI",
    salary: "650k - 950k FCFA",
    posted: "Il y a 4 jours",
    description: "Créez des applications mobiles performantes pour iOS et Android avec une équipe talentueuse.",
    tags: ["React Native", "iOS", "Android", "Mobile"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "8",
    title: "Chargé de Recherche UX",
    company: "UserFirst Design",
    location: "Douala, Cameroun",
    type: "CDD",
    salary: "500k - 750k FCFA",
    posted: "Il y a 6 jours",
    description: "Menez des recherches utilisateur pour informer les décisions produit. Planifiez et exécutez des études de recherche.",
    tags: ["Recherche utilisateur", "Qualitatif", "Quantitatif", "Tests d'utilisabilité"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "9",
    title: "Chef de Projet IT",
    company: "Digital Solutions CM",
    location: "Yaoundé, Cameroun",
    type: "CDI",
    salary: "700k - 1M FCFA",
    posted: "Il y a 2 jours",
    description: "Gérez des projets informatiques de bout en bout, de la conception à la livraison. Coordonnez les équipes techniques.",
    tags: ["Gestion de projet", "Agile", "Scrum", "Leadership"],
    isNew: true,
    isUrgent: false,
  },
  {
    id: "10",
    title: "Comptable Senior",
    company: "Finance Plus",
    location: "Douala, Cameroun",
    type: "CDI",
    salary: "450k - 700k FCFA",
    posted: "Il y a 3 jours",
    description: "Recherche d'un comptable expérimenté pour superviser la comptabilité générale et les rapports financiers.",
    tags: ["Comptabilité", "OHADA", "Excel", "SAP"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "11",
    title: "Gestionnaire des Ressources Humaines",
    company: "HR Solutions Cameroun",
    location: "Yaoundé, Cameroun",
    type: "CDI",
    salary: "600k - 850k FCFA",
    posted: "Il y a 2 jours",
    description: "Gérez le recrutement, la formation et le développement des talents. Assurez la conformité aux réglementations du travail.",
    tags: ["RH", "Recrutement", "Formation", "Gestion des talents"],
    isNew: true,
    isUrgent: false,
  },
  {
    id: "12",
    title: "Spécialiste Cybersécurité",
    company: "SecureNet Africa",
    location: "Douala, Cameroun (Hybride)",
    type: "CDI",
    salary: "900k - 1.3M FCFA",
    posted: "Il y a 1 jour",
    description: "Protégez nos systèmes contre les menaces cybernétiques. Effectuez des audits de sécurité et des tests de pénétration.",
    tags: ["Cybersécurité", "Pentesting", "Sécurité réseau", "CISSP"],
    isNew: true,
    isUrgent: true,
  },
  {
    id: "13",
    title: "Ingénieur Commercial",
    company: "Telecom Solutions",
    location: "Garoua, Cameroun",
    type: "CDI",
    salary: "500k - 800k FCFA",
    posted: "Il y a 5 jours",
    description: "Développez notre portefeuille clients dans le secteur des télécommunications. Présentez nos solutions techniques.",
    tags: ["Vente", "B2B", "Télécommunications", "Négociation"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "14",
    title: "Analyste Financier",
    company: "Investment Group CM",
    location: "Douala, Cameroun",
    type: "CDI",
    salary: "650k - 950k FCFA",
    posted: "Il y a 3 jours",
    description: "Analysez les données financières, préparez des rapports et des prévisions pour soutenir les décisions stratégiques.",
    tags: ["Finance", "Analyse", "Excel", "Modélisation financière"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "15",
    title: "Enseignant Informatique",
    company: "Université de Yaoundé",
    location: "Yaoundé, Cameroun",
    type: "CDD",
    salary: "400k - 600k FCFA",
    posted: "Il y a 1 semaine",
    description: "Enseignez les sciences informatiques aux étudiants de licence et master. Contribuez à la recherche académique.",
    tags: ["Enseignement", "Informatique", "Pédagogie", "Recherche"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "16",
    title: "Architecte Logiciel",
    company: "Enterprise Tech",
    location: "Douala, Cameroun (À distance)",
    type: "CDI",
    salary: "1M - 1.5M FCFA",
    posted: "Il y a 2 jours",
    description: "Concevez l'architecture technique de nos applications d'entreprise. Guidez les équipes de développement.",
    tags: ["Architecture", "Microservices", "Cloud", "Leadership technique"],
    isNew: true,
    isUrgent: false,
  },
  {
    id: "17",
    title: "Infirmier(ère) Diplômé(e)",
    company: "Hôpital Général de Douala",
    location: "Douala, Cameroun",
    type: "CDI",
    salary: "350k - 550k FCFA",
    posted: "Il y a 4 jours",
    description: "Prodiguez des soins de qualité aux patients. Travaillez en équipe multidisciplinaire dans un environnement hospitalier.",
    tags: ["Santé", "Soins infirmiers", "Médical", "Diplôme d'État"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "18",
    title: "Community Manager",
    company: "Social Media Agency CM",
    location: "Yaoundé, Cameroun (À distance)",
    type: "Freelance",
    salary: "300k - 500k FCFA",
    posted: "Il y a 1 jour",
    description: "Gérez les réseaux sociaux de nos clients. Créez du contenu engageant et analysez les performances.",
    tags: ["Réseaux sociaux", "Content creation", "Community management", "Analytics"],
    isNew: true,
    isUrgent: false,
  },
  {
    id: "19",
    title: "Agronome",
    company: "AgroTech Cameroun",
    location: "Bafoussam, Cameroun",
    type: "CDI",
    salary: "450k - 700k FCFA",
    posted: "Il y a 6 jours",
    description: "Conseillez les agriculteurs sur les pratiques agricoles modernes. Supervisez les projets de développement agricole.",
    tags: ["Agriculture", "Agronomie", "Développement rural", "Conseil"],
    isNew: false,
    isUrgent: false,
  },
  {
    id: "20",
    title: "Juriste d'Entreprise",
    company: "Cabinet Juridique Excellence",
    location: "Yaoundé, Cameroun",
    type: "CDI",
    salary: "600k - 900k FCFA",
    posted: "Il y a 3 jours",
    description: "Conseillez sur les questions juridiques de l'entreprise. Rédigez et révisez les contrats commerciaux.",
    tags: ["Droit", "Contrats", "Juridique", "Corporate"],
    isNew: false,
    isUrgent: false,
  },
];

// Exporter les données
export default jobsData; // Export par défaut

// Optionnel : exporter aussi le type pour l'utiliser ailleurs
// export type { Job };